version: "3.8"

name: twitchbot

services:
  db:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - twitchbot:/var/lib/postgresql
      - twitchbot_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
        reservations:
          cpus: "0.01"
          memory: 50M
    networks:
      - tbot

volumes:
  twitchbot:
  twitchbot_data:

networks:
  tbot:
    driver: bridge
