spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    enabled: true


twitch:
  oauth:
    client_id: ${CLIENT_ID}
    scopes:
      - chat:read
      - chat:edit
      - channel:read:subscriptions
      - channel:moderate
      - moderator:read:chatters
      - moderator:manage:shoutouts
      - moderator:read:followers
    retry: 10
    timeout: 6
    timeout-unit: SECONDS
  saint:
    url: ${SAINT_URL}