databaseChangeLog:
  - changeSet:
      id: 0-0-2-2
      author: damnardev
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: t_raid_configuration_pkey
                  name: id
                  type: BIGINT
              - column:
                  name: raid_message_enabled
                  type: BOOLEAN
              - column:
                  name: twitch_shoutout_enabled
                  type: BOOLEAN
              - column:
                  name: wizebot_shoutout_enabled
                  type: BOOLEAN
            tableName: t_raid_configuration
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                  name: raid_configuration_id
                  type: BIGINT
              - column:
                  name: message
                  type: VARCHAR(255)
            tableName: t_raid_configuration_message
        - addForeignKeyConstraint:
            baseColumnNames: id
            baseTableName: t_raid_configuration
            constraintName: t_raid_configuration_channel_fk
            deferrable: false
            initiallyDeferred: false
            onDelete: NO ACTION
            onUpdate: NO ACTION
            referencedColumnNames: id
            referencedTableName: t_channel
            validate: true
        - addForeignKeyConstraint:
            baseColumnNames: raid_configuration_id
            baseTableName: t_raid_configuration_message
            constraintName: t_raid_configuration_message_raid_fk
            deferrable: false
            initiallyDeferred: false
            onDelete: NO ACTION
            onUpdate: NO ACTION
            referencedColumnNames: id
            referencedTableName: t_raid_configuration
            validate: true
        - sqlFile:
            path: db/sql/v0_0_2/db.update.001-copy.sql
        - dropTable:
            tableName: t_channel_raid_message
        - dropTable:
            tableName: t_channel_raid
