on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: s4u/setup-maven-action@v1.17.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: 3.9.9

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
