on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 & Maven 3.9.9
        uses: s4u/setup-maven-action@v1.17.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: 3.9.9

      - name: Build with Maven
        env:
          TOKEN: ${{ secrets.SONAR_TOKEN }}
          URI: ${{ vars.SONAR_URI }}
        run: |
          mvn clean verify sonar:sonar -Dsonar.host.url=$URI -Dsonar.login=$TOKEN --batch-mode --update-snapshots
