on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          TOKEN: ${{ secrets.SONAR_TOKEN }}
          URI: ${{ vars.SONAR_URI }}
        run: mvn clean verify sonar:sonar -Dsonar.host.url=$URI -Dsonar.login=$TOKEN --batch-mode --update-snapshots
